# Generated by Django 5.1.5 on 2025-01-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_user_login_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
