# Generated by Django 5.1.5 on 2025-02-17 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
