# Generated by Django 5.1.5 on 2025-02-18 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
