# Generated by Django 5.1.5 on 2025-03-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_delete_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='history',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='nid',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='patient',
            name='pid',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
