# Generated by Django 5.1.5 on 2025-03-06 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_remove_patient_history_remove_patient_nid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='pid',
        ),
    ]
