# Generated by Django 5.1.5 on 2025-03-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_patient_history_patient_uploaded_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
