# Generated by Django 5.1.5 on 2025-03-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pno_verified',
            field=models.BooleanField(default=False),
        ),
    ]
