# Generated by Django 5.1.5 on 2025-03-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_patient_pno_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='uploaded_files',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
