# Generated by Django 5.1.5 on 2025-01-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0044_appointment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_information',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
