# Generated by Django 5.1.5 on 2025-01-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0045_doctor_information_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_information',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
