# Generated by Django 5.1.5 on 2025-03-06 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0046_doctor_information_profile_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_information',
            old_name='nid',
            new_name='regid',
        ),
    ]
