# Generated by Django 5.1.5 on 2025-03-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0047_rename_nid_doctor_information_regid'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_information',
            name='regid_verified',
            field=models.BooleanField(default=False),
        ),
    ]
